version: '3'
services:
   shiny:
      container_name: airsensor-shiny-test
      image: airsensor-shiny-test
      ports: 
          - "6709:3838"
      volumes: 
          - /var/www/tools.mazamascience.com/html/logs/airsensor-shiny/test/app:/srv/shiny-server/logs
          - /var/www/tools.mazamascience.com/html/logs/airsensor-shiny/test/app:/var/log/shiny-server/
      restart: unless-stopped
  
#networks:
#  custom:
#    driver: bridge
#    ipam:
#      driver: default
#      config:
#        - subnet: 172.67.09.0/24
#          gateway: 172.67.09.1
