version: '3'
services:
   shiny:
      container_name: airsensor-shiny-desktop
      image: airsensor-shiny-desktop
      ports: 
          - "8080:3838"
      volumes: 
          - ${PWD}/logs:/var/log/shiny-server/
      restart: unless-stopped       
